services:
#    og_send_grid.example:
#        class: OG\SendGridBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  og_send_grid.provider:
    class: OG\SendGridBundle\Provider\SendGridProvider
    arguments:
      - '%og_send_grid.api_key%'
      - '%og_send_grid.disable_delivery%'
      - '%og_send_grid.web_profiler%'
      - '@debug.stopwatch'
    public: true

  og_send_grid.data_collector:
    class: OG\SendGridBundle\DataCollector\SendGridDataCollector
    arguments:
      - '@og_send_grid.provider'
      - '%og_send_grid.web_profiler%'
      - '@debug.stopwatch'
    tags:
    - name: data_collector
      template: '@OGSendGrid/WebProfiler/index.html.twig'
      id: 'og_send_grid.data_collector'
    public: false