services:
#    og_send_grid.example:
#        class: OG\SendGridBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  og_send_grid.provider:
    class: OG\SendGridBundle\Provider\SendGridProvider
    arguments:
      - '%og_send_grid.api_key%'
      - '%og_send_grid.disable_delivery%'
      - '%og_send_grid.web_profiler%'
      - '%og_send_grid.redirect_to%'
      - '@event_dispatcher'
    public: true

  og_send_grid.data_collector:
    class: OG\SendGridBundle\DataCollector\SendGridDataCollector
    arguments:
      - '%og_send_grid.web_profiler%'
      - '@debug.stopwatch'
      - '@og_send_grid.storage.mail_log'
    tags:
    - name: data_collector
      template: '@OGSendGrid/WebProfiler/index.html.twig'
      id: 'og_send_grid.data_collector'
    public: false

  og_send_grid.subscriber.send_grid:
    class: OG\SendGridBundle\EventSubscriber\SendGridEventSubscriber
    arguments:
      - '%og_send_grid.web_profiler%'
      - '@debug.stopwatch'
      - '@og_send_grid.storage.mail_log'
    tags:
        - { name: kernel.event_subscriber }

  og_send_grid.subscriber.webhook:
    class: OG\SendGridBundle\EventSubscriber\WebHookEventSubscriber

  og_send_grid.storage.mail_log:
    class: OG\SendGridBundle\Storage\MailLogStorage
    public: true